const comment =
  '// Autogenerated file, DO NOT MODIFY or it will be overwritten';

const template = (variables, { tpl }) => {
  const componentName = variables.componentName.replace('Svg', '');
  return tpl`
${comment}
${variables.imports};

${variables.interfaces};
import { ficus } from 'react-native-ficus-ui';

const _Svg = (${variables.props}) => (
  ${variables.jsx}
);

const ${componentName} = ficus(_Svg)

export default ${componentName};
`;
};

// eslint-disable-next-line no-undef
module.exports = {
  outDir: './src/components/icons/generated',
  typescript: true,
  replaceAttrValues: {
    '#000': 'currentColor',
    none: 'currentColor',
    black: 'currentColor',
  },
  expandProps: true,
  template,
  native: true,
  svgo: true,
  svgoConfig: {
    plugins: [
      {
        name: 'removeAttrs',
        params: {
          attrs: '(xmlns)',
        },
      },
    ],
  },

  // Prevent svgr + prettier 3 compatibility issue
  // It is ok to disable it here, generation script will run prettier
  // See https://github.com/gregberge/svgr/issues/893 for details on the underlying issue
  prettier: false,
};
