name: 🎭 E2E Tests

env:
  EXPO_PUBLIC_API_URL: ${{ vars.API_URL }}
  EXPO_PUBLIC_AUTH_URL: ${{ vars.AUTH_URL }}
  EXPO_PUBLIC_OPENAPI_URL: ${{ vars.OPENAPI_URL }}

on:
  workflow_dispatch:
  push:
    branches: [test/e2e, test/e2e/**]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  e2e-full:
    name: 🎭 Full E2E Tests
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Enable KVM
        run: sudo chmod 777 /dev/kvm

      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: 🏗 Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔨 Prebuild & Build APK (release)
        run: |
          APP_ENV=production npx expo prebuild --clean --platform android
          sed -i 's/minifyEnabled true/minifyEnabled false/g' android/app/build.gradle
          sed -i 's/shrinkResources true/shrinkResources false/g' android/app/build.gradle
          cd android && ./gradlew assembleRelease --no-daemon --max-workers 2 \
            -Pandroid.injected.signing.store.file=$HOME/.android/debug.keystore \
            -Pandroid.injected.signing.store.password=android \
            -Pandroid.injected.signing.key.alias=androiddebugkey \
            -Pandroid.injected.signing.key.password=android

      - name: 🎭 Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash && echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: 🤖 Run full E2E tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          pre-emulator-launch-script: |
            echo "persist.sys.locale=en-US" >> $HOME/.android/avd/test.avd/config.ini
            echo "persist.sys.language=en" >> $HOME/.android/avd/test.avd/config.ini
            echo "persist.sys.country=US" >> $HOME/.android/avd/test.avd/config.ini
          script: |
            adb kill-server
            adb start-server
            adb wait-for-device
            sleep 5
            adb uninstall com.bearstudio.startuinative || true
            adb install android/app/build/outputs/apk/release/app-release.apk
            pnpm test:e2e
